### ISSUE TITLE
Prazo de desenvolvimento

### ISSUE THREAD

**Issue by vanderjuh** [ForLogic/desafio-4-devs#10]
Olá, pessoal da Forlogic. Gostária de saber quanto tempo tenho para desenvolver o desafio?

**Comment by mvmjacobs** [comment]
E aí Vanderley, tudo bem com você?

Existem duas possíveis situações:

1. Se você enviou o seu currículo ou entrou em contato com a ForLogic através das plataformas de seleção, alguém do RH vai entrar em contato com você e vai te passar o prazo para envio.

2. Se você encontrou o desafio no GitHub e quer enviar a sua solução, basta enviar. Não existe um prazo fixo nessa situação, sinta-se a vontade para levar o tempo que você achar necessário.

> Nota: Em média os candidatos que nos enviam o desafio levam em torno de 7 a 10 dias.

Consegui esclarecer sua dúvida?
