### ISSUE TITLE
Prazo

### ISSUE THREAD

**Issue by Gabrielbemo** [ForLogic/desafio-4-devs#11]
Oi, Qual é o prazo para enviar o projeto.

**Comment by mvmjacobs** [comment]
Fala Gabriel, tudo certo?

Existem duas possíveis situações:

1. Se você enviou o seu currículo ou entrou em contato com a ForLogic através das plataformas de seleção, alguém do RH vai entrar em contato com você e vai te passar o prazo para envio.

2. Se você encontrou o desafio no GitHub e quer enviar a sua solução, basta enviar. Não existe um prazo fixo nessa situação, sinta-se a vontade para levar o tempo que você achar necessário.

> Nota: Em média os candidatos que nos enviam o desafio levam em torno de 7 a 10 dias.

Se você ficou com dúvidas, pode responder aqui que eu vou esclarecer melhor.
Abraço!

**Comment by Gabrielbemo** [comment]
Tudo beleza, eu me candidatei a vaga na plataforma Gupy, essa seria uma plataforma de seleção ?

**Comment by mvmjacobs** [comment]
Opa Gabriel!

O Gupy é uma das plataformas sim.

Bom, esse desafio aqui é um dos passos da nossa seleção. Em relação ao prazo, se ninguém do RH entrou em contato com você ainda, siga a segunda situação que eu mencionei acima, assim que terminar basta envia-lo (você pode submeter o link do seu projeto em uma issue aqui ou enviar um email direto pra mim no marcos@forlogic.net).

É muito provável que alguém do RH entre em contato com você para enviar algumas instruções e o prazo para desenvolvimento, se isso acontecer, siga o prazo que eles enviarem. 

Beleza? Qualquer coisa pode responder aqui que eu te ajudo! xD

**Comment by Gabrielbemo** [comment]
Beleza ! Obrigado.

Em qui, 27 de set de 2018 às 19:33, Marcos Vinicius Jacobs <
notifications@github.com> escreveu:
