### ISSUE TITLE
Como utilizar a API?

### ISSUE THREAD

**Issue by beatrizbenz** [ForLogic/desafio-4-devs#13]
Olá, boa tarde!

Gostaria muito de saber utilizar a API, mas estou tendo dificuldade. Li que precisa Header com "Authorization", Value:"meu-projeto", mas não ficou claro para mim, como crio o header. Eu criei um projeto no Firebase e estou com o código do projeto.

**Comment by mvmjacobs** [comment]
Oi, Beatriz!

Como setar o Header da requisição vai depender de qual linguagem você está utilizando.

Se o seu projeto for em JavaScript, você pode utilizar como base esses dois exemplos, um usando [AJAX](https://stackoverflow.com/questions/10093053/add-header-in-ajax-request-with-jquery) e este outro usando apenas [JS](https://stackoverflow.com/questions/19661157/how-to-add-header-data-in-xmlhttprequest-when-using-formdata).

Caso o seu projeto seja em outra linguagem, você pode procurar exemplos de como setar o Header da requisição nessa linguagem.

Caso você continue tendo dificuldades fique a vontade pra comentar aqui que eu vou tentar te ajudar.

**Comment by beatrizbenz** [comment]
Muito obrigada, irei estudar! :)
