### ISSUE TITLE
Dúvida sobre a entrega

### ISSUE THREAD

**Issue by jelufe** [ForLogic/desafio-4-devs#14]
Quando o projeto estiver concluído por onde devo passar o link do meu repositório?

**Comment by mvmjacobs** [comment]
Olá, Jean!

Você pode enviar o link do repositório para o email gente@forlogic.net.

Qualquer outra dúvida fique a vontade pra abrir uma issue ou, se preferir, você pode mandar um email direto pra mim no email marcos@fologic.net.
