### ISSUE TITLE
405

### ISSUE THREAD

**Issue by gardheamsantos00** [ForLogic/desafio-4-devs#2]
quando faço um POST para http://desafio4devs.forlogic.net/api/evaluations/  retorna um 405 method not allowed , não suporta method POST , o header está com authorization e nome do projeto firebase corretos, no body da req está no formato do exemplo, o que posso está fazendo de errado ?
as requisicões por enquanto estão sendo feitas pelo postman pra test inicial ...
todas as req   /costumers estão funcionando normal ...

**Comment by mvmjacobs** [comment]
Opa, você não fez nada de errado mesmo. O problema estava com o método POST da controller de avaliações, onde faltava uma anotação de rota.

Acabei de corrigir e agora já está funcionando normal, mas mesmo assim, desculpa a demora pelo retorno.
