### ISSUE TITLE
Problema ao comunicar com a API por AJAX

### ISSUE THREAD

**Issue by vinibs** [ForLogic/desafio-4-devs#3]
Estou tentando realizar a comunicação com a API. 
Entretanto, quando realizo uma requisição por AJAX (seja JS puro ou jQuery), eu recebo o aviso de que a requisição foi bloqueada devido à falta de cabeçalho "Access-Control-Allow-Origin" (no Chrome e Firefox) ou que a requisição simplesmente não foi respondida (no Safari). No Chrome e no Firefox também acontece de exibir status 405 ao realizar a requisição, avaliando as requisições na aba "Network" das ferramentas de desenvolvedor.

Exemplo no Firefox:
![screen shot 2018-06-19 at 11 42 51](https://user-images.githubusercontent.com/20691391/41604558-ed25f6ba-73b5-11e8-954a-a165e5061153.png)

![screen shot 2018-06-19 at 11 53 56](https://user-images.githubusercontent.com/20691391/41605300-89740ae2-73b7-11e8-848d-b13308ea3f36.png)

Exemplo no Safari:
![screen shot 2018-06-19 at 11 55 05](https://user-images.githubusercontent.com/20691391/41605366-a955d03e-73b7-11e8-8c15-11a18baf030d.png)

![screen shot 2018-06-19 at 11 51 42](https://user-images.githubusercontent.com/20691391/41605149-39852d9a-73b7-11e8-87ac-26c9a270dbff.png)

O código utilizado é esse:
`var xhr = new XMLHttpRequest();`
 `xhr.open('GET', 'http://desafio4devs.forlogic.net/api/customers', true);`
`xhr.setRequestHeader('Authorization', 'projeto-forlogic');`
`xhr.send();`

Entretanto, utilizando o Chrome com a flag de desabilitar a segurança, consegui fazer uma requisição, aparentemente bem-sucedida, que retornou um erro de comunicação com o Firebase:
![screen shot 2018-06-19 at 11 48 53](https://user-images.githubusercontent.com/20691391/41604957-c833fbb2-73b6-11e8-96fd-6f4dc47b170c.png)

Curiosamente, quando fiz o teste utilizando o app Postman, não foi exibido nenhum tipo de erro (nem mesmo da comunicação com o Firebase).

Assim, não sei ao certo se o problema está no código cliente, se está no browser ou se pode ser alguma falha de conceito ou problema com a comunicação com a API.

**Comment by mvmjacobs** [comment]
E ai Vinicius, tudo bem com você? Eu espero que sim!

Cara, quando eu fiz a API eu testei somente com o Postman. Não tinha percebido que estava com esse problema em requisições via `localhost`. Eu acabei de fazer algumas adaptações na API para que seja possível fazer as requisições.

Também realizei um teste utilizando o seu código no Opera, Chrome e no Mozilla e agora foi possível realizar a requisição normalmente.

Qualquer dúvida fique a vontade p/ abrir uma issue.

**Comment by vinibs** [comment]
Olá!
Bacana, agora funcionou aqui, mesmo.
Só gostaria de saber se tem alguma ideia do que pode estar dando esse erro com o Firebase. Já tentei com os dados fornecidos como "Código do projeto" (conforme o código que coloquei), "Nome do projeto" e "Nome exibido ao público" e em nenhum deles consegui o retorno correto (vazio, até o momento), sempre dando este erro que comentei anteriormente.

**Comment by mvmjacobs** [comment]
Então, eu fiz um teste aqui com o código do projeto que você passou (`projeto-forlogic`) e o retorno dele é vazio mesmo. Isso acontece porque nesse projeto que você criou no Firebase ainda não foi inserido nenhum registro.

Faça uma requisição do tipo `POST`, inserindo um registro no banco, aí assim que um registro for inserido a requisição `GET` que você está fazendo já vai retornar alguma coisa.

Você pode [consultar aqui](https://github.com/ForLogic/desafio-4-devs/blob/master/API/API%20Setup.md#post-apicustomers) como inserir um registro via `POST`.

**Comment by vinibs** [comment]
Sim, o conteúdo é vazio mesmo. O problema que estou tendo é a mensagem `"error":"Firebase error. Please ensure that you spelled the name of your Firebase correctly"`. Estou checando as configurações do projeto de do banco de dados no momento pra ver se encontro alguma explicação para o que pode estar acontecendo, se estou passando dados errados, essas coisas.

**Comment by mvmjacobs** [comment]
Eu testei o mesmo código que você passou, inclusive com o mesmo código do projeto do Firebase, em 3 navegadores e nenhum apresentou essa mensagem que você está recebendo.

Verifique se isso não está acontecendo por causa da flag de desabilitar a segurança do Chrome, que você citou acima.

**Comment by vinibs** [comment]
Consegui. Na verdade o problema era no código mesmo.
Porque aqui estou usando uma estrutura menos direta, por assim dizer, pra fazer a requisição, e o nome do projeto estava salvo em uma variável, aí o problema estava na leitura dessa variável.
Obrigado pela ajuda!

**Comment by mvmjacobs** [comment]
Ah sim, entendi, mas legal que você tenha conseguido. o/
