### ISSUE TITLE
Como são realizadas as avaliações por parte dos clientes?

### ISSUE THREAD

**Issue by vinibs** [ForLogic/desafio-4-devs#4]
Lendo o escopo me deparei com essa dúvida.
Apenas são colocados os cadastros de dados do cliente - inclusive, achei que "cliente" e "nome do contato" ficaram confusos (cliente seria uma empresa?) - e de avaliações, que vinculam os clientes à avaliação. Entretanto não ficou claro como a avaliação, por parte do cliente, deve ser realizada dentro da aplicação, dado que não há, primariamente, nenhum sistema de acesso por meio do cliente à aplicação.
Como devo prosseguir com esta etapa?

**Comment by lucasfcoelho1** [comment]
Opa @vinibs , no caso o cliente é uma empresa sim e o nome do contato seria uma pessoa que trabalha nessa empresa e que geralmente é quem responde as perguntas sobre NPS.

Em relação a parte da avaliação, a parte principal seria existir um sistema que gerenciasse e auxiliasse o profissional que precisa realizar a pesquisa todos os meses. A forma de contato para a pesquisa com o cliente inicialmente pode ser por telefone, e-mail, SMS, etc. Para esse projeto não é obrigatório que o cliente tenha um acesso direto ao sistema, a não ser que você queira fazer, sinta-se livre para escolher. Contudo o foco principal é construir a gerencia para a empresa que realiza a pesquisa.

**Comment by lucasfcoelho1** [comment]
Dê uma olhada nesses links, eles podem te ajudar:

[Vídeo: NPS em 3 minutos](https://www.youtube.com/watch?v=s9RMxaMGWj8)
[Wiki NPS](https://pt.wikipedia.org/wiki/Net_Promoter_Score#Funcionamento)

**Comment by vinibs** [comment]
Então posso considerar que as respostas seriam preenchidas diretamente no banco de dados?

**Comment by lucasfcoelho1** [comment]
Poderia, porém a pesquisa de NPS em um cenário real geralmente não é feita por desenvolvedores, geralmente um pessoal da QA ou atendimento ao cliente e que não tem muito conhecimento técnico em relação a desenvolvimento. Então pra um cenário real seria mais interessante que tudo pudesse ser feito por uma interface amigável ao usuário.

**Comment by vinibs** [comment]
Certo.
Farei então uma tela para a realização da avaliação.
Obrigado pela ajuda!
