### ISSUE TITLE
A API se comunica com um banco configurado no Firebase via REST

### ISSUE THREAD

**Issue by thiagoalmeida88** [ForLogic/desafio-4-devs#5]
Boa tarde prezados. Criei o banco https://pesquisa-satisfacao.firebaseio.com/ e estou com dificuldade de entender como devo fazer com que a API se comunique com ele. Por exemplo: tenho já a tela de cadastro de clientes. Como faço para gravar os dados? Seria direto na API disponibilizada ou no banco que criei? []'s

**Comment by lucasfcoelho1** [comment]
Opa Thiago, então cara, se você configurou o seu banco como diz nesse pequeno manualzinho de [como criar um banco no Firebase](https://github.com/ForLogic/desafio-4-devs/blob/master/API/Firebase%20Setup.md), basta que você faça como pede na primeira parte do manual da [API](https://github.com/ForLogic/desafio-4-devs/blob/master/API/API%20Setup.md#headers-obrigat%C3%B3rios).

Quando você passa no Header da requisição o código do seu banco, a API irá enviar automagicamente para o seu Firebase. Por exemplo quando você manda um POST como este [aqui](https://github.com/ForLogic/desafio-4-devs/blob/master/API/API%20Setup.md#post-apicustomers), a API salvará o cliente no Firebase.

**Comment by thiagoalmeida88** [comment]
Certo. Lucas, desculpe perguntar, é que eu nunca havia utilizado o firebase. Ainda não consegui configurar conforme as orientações do manual e demais informações. Como eu faço para inserir o Key: "Authorization", Value:"nome-do-seu-projeto-10cd8" para cada requisição a fim de utilizar os métodos? Passando por URL? Como eu faria?

**Comment by lucasfcoelho1** [comment]
A forma de fazer depende de qual linguagem você está utilizando...

Qual é a sua linguagem?
Tenta procurar como adicionar como adicionar parâmetros no header da requisição.

**Comment by thiagoalmeida88** [comment]
JavaScript. Blz.

**Comment by lucasfcoelho1** [comment]
Pra JavaScript eu encontrei dois exemplos, esse usando [AJAX](https://stackoverflow.com/questions/10093053/add-header-in-ajax-request-with-jquery) e este outro usando apenas [JS](https://stackoverflow.com/questions/19661157/how-to-add-header-data-in-xmlhttprequest-when-using-formdata).

Espero que ajude.

**Comment by thiagoalmeida88** [comment]
Certo. Vlw pela informação. Abs
