### ISSUE TITLE
Cada avaliação é composta por 20% dos clientes cadastrados

### ISSUE THREAD

**Issue by joaojvf** [ForLogic/desafio-4-devs#6]
No escopo apresenta a seguinte regra de negócio:
*Cada avaliação é composta por 20% dos clientes cadastrados;

Devo seguir literalmente o pedido? Pois, por exemplo, caso a empresa tenha um número pequeno de clientes, não poderá ser feita a pesquisa. Qual melhor forma de prosseguir nesse caso?

**Comment by mvmjacobs** [comment]
E aí João, tudo bem?

Você pode seguir a regra como ela foi descrita mesmo. Os 20% só será um problema caso a empresa possua menos de 5 clientes, então você pode considerar que a empresa sempre terá no minimo 5 clientes e isso não será um problema. Ok? Era essa sua dúvida?

**Comment by joaojvf** [comment]
Beleza, era só para confirmar isso mesmo. 
Obrigado!
