### ISSUE TITLE
Dúvida sobre as avaliações

### ISSUE THREAD

**Issue by thalesdeluca** [ForLogic/desafio-4-devs#8]
As avaliações individuais seriam feitas manualmente aos clientes todo mês? Ou seria feita uma única vez e para o resultado mensal seriam selecionados de forma automática e randômica 20% dos clientes já cadastrados?

**Comment by mvmjacobs** [comment]
E aí Thales, tudo bem?

Então, para fazer uma avaliação são selecionados 20% dos clientes cadastrados. Agora se essa seleção vai ser feita manualmente por quem vai executar a avaliação ou se a aplicação vai sugerir de forma aleatória os 20% vai depender de como você vai implementar, nesse casso as duas formas de selecionar são corretas.

Só vale lembrar que um cliente que participou de uma avaliação em um mês só pode participar novamente após duas avaliações.

Era essa sua dúvida? Consegui responder?

**Comment by thalesdeluca** [comment]
Sim era essa minha dúvida. É que eu estava cadastrando o usuario e logo em seguida fazendo a avaliação. 

Vlw ^^

**Comment by mvmjacobs** [comment]
Ah sim, entendi! 

Qualquer outra dúvida fique a vontade pra perguntar!
