### ISSUE TITLE
Dúvida sobre a API e o Firebase

### ISSUE THREAD

**Issue by thalesdeluca** [ForLogic/desafio-4-devs#9]
Por enquanto estou armazenando meus dados em um Firebase que eu mesmo criei. Ao término dos testes, devo trocar a referencia do Firebase Database para o endereço da API? No caso, estou fazendo a aplicação Mobile.

**Comment by mvmjacobs** [comment]
Olá, Thales!

Pode deixar o que você está utilizando mesmo. De qualquer forma nós conseguiremos testar e avaliar o seu projeto.
